<?php

/**
 * This is the model base class for the table "modulo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Modulo".
 *
 * Columns in table "modulo" available as properties of the model,
 * followed by relations of table "modulo" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property integer $empreendimento
 * @property integer $ativo
 *
 * @property Bloco[] $blocos
 * @property Empreendimento $empreendimento0
 */
abstract class BaseModulo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modulo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Modulo|Modulos', $n);
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao, empreendimento, ativo', 'required'),
			array('empreendimento, ativo', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>255),
			array('id, descricao, empreendimento, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'blocos' => array(self::HAS_MANY, 'Bloco', 'modulo'),
			'empreendimento0' => array(self::BELONGS_TO, 'Empreendimento', 'empreendimento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'descricao' => Yii::t('app', 'Descricao'),
			'empreendimento' => null,
			'ativo' => Yii::t('app', 'Ativo'),
			'blocos' => null,
			'empreendimento0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('empreendimento', $this->empreendimento);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}