<?php

/**
 * This is the model base class for the table "movimentacao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Movimentacao".
 *
 * Columns in table "movimentacao" available as properties of the model,
 * followed by relations of table "movimentacao" available as properties of the model.
 *
 * @property integer $id
 * @property integer $material
 * @property double $quantidade
 * @property string $data
 * @property integer $tipo_movimentacao
 * @property integer $usuario
 * @property integer $ativo
 *
 * @property Usuario $usuario0
 * @property Material $material0
 * @property TipoMovimentacao $tipoMovimentacao0
 */
abstract class BaseMovimentacao extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'movimentacao';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Movimentação|Movimentações', $n);
    }

    public static function representingColumn() {
        return 'data';
    }

    public function rules() {
        return array(
            array('material, quantidade, data, tipo_movimentacao, usuario', 'required'),
            array('material, tipo_movimentacao, usuario, ativo', 'numerical', 'integerOnly' => true),
            array('quantidade', 'numerical'),
            array('descricao', 'length', 'max' => 255),
            array('ativo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, material, descricao, quantidade, data, tipo_movimentacao, usuario, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'usuario0' => array(self::BELONGS_TO, 'Usuario', 'usuario'),
            'material0' => array(self::BELONGS_TO, 'Material', 'material'),
            'tipoMovimentacao0' => array(self::BELONGS_TO, 'TipoMovimentacao', 'tipo_movimentacao'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'material' => null,
            'descricao' => Yii::t('app', 'Descrição'),
            'quantidade' => Yii::t('app', 'Quantidade'),
            'data' => Yii::t('app', 'Data'),
            'tipo_movimentacao' => null,
            'usuario' => null,
            'ativo' => Yii::t('app', 'Ativo'),
            'usuario0' => null,
            'material0' => null,
            'tipoMovimentacao0' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('material', $this->material);
        $criteria->compare('descricao', $this->descricao);
        $criteria->compare('quantidade', $this->quantidade);
        $criteria->compare('data', $this->data, true);
        $criteria->compare('tipo_movimentacao', $this->tipo_movimentacao);
        $criteria->compare('usuario', $this->usuario);
        $criteria->compare('ativo', 1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                'defaultOrder'=>'data DESC',
            ),
        ));
    }

}
