<?php

/**
 * This is the model base class for the table "empreendimento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empreendimento".
 *
 * Columns in table "empreendimento" available as properties of the model,
 * followed by relations of table "empreendimento" available as properties of the model.
 *
 * @property integer $id
 * @property string $logo
 * @property string $implantacao
 * @property string $implantacao_full
 * @property integer $dias_reserva
 * @property integer $andares
 * @property string $nome
 * @property integer $ativo
 *
 * @property Bloco[] $blocos
 */
abstract class BaseEmpreendimento extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'empreendimento';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Empreendimento|Empreendimentos', $n);
    }

    public static function representingColumn() {
        return 'nome';
    }

    public function rules() {
        return array(
            array('logo, implantacao, dias_reserva, comissao_corretor, comissao_adm_vendas, nome, ativo', 'required'),
            array('comissao_corretor, comissao_adm_vendas', 'numerical'),
            array('dias_reserva, andares', 'numerical', 'integerOnly' => true),
            array('logo, implantacao, implantacao_full', 'length', 'max' => 100),
            array('nome', 'length', 'max' => 60),
            array('id, logo, implantacao, dias_reserva, nome, andares, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'blocos' => array(self::HAS_MANY, 'Bloco', 'empreendimento'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'logo' => Yii::t('app', 'Logo'),
            'implantacao' => Yii::t('app', 'Implantação'),
            'implantacao_full' => Yii::t('app', 'Implantação Alta Qualidade'),
            'dias_reserva' => Yii::t('app', 'Dias Reserva'),
            'andares' => Yii::t('app', 'Andares'),
            'comissao_corretor' => Yii::t('app', 'Comissão Corretor'),
            'comissao_adm_vendas' => Yii::t('app', 'Comissão Adm. de Vendas'),
            'nome' => Yii::t('app', 'Nome'),
            'ativo' => Yii::t('app', 'Ativo'),
            'blocos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('logo', $this->logo, true);
        $criteria->compare('implantacao', $this->implantacao, true);
        $criteria->compare('implantacao_full', $this->implantacao_full, true);
        $criteria->compare('dias_reserva', $this->dias_reserva);
        $criteria->compare('andares', $this->dias_reserva);
        $criteria->compare('nome', $this->nome, true);
        $criteria->compare('ativo', $this->ativo);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}