<?php

/**
 * This is the model base class for the table "atividade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Atividade".
 *
 * Columns in table "atividade" available as properties of the model,
 * followed by relations of table "atividade" available as properties of the model.
 *
 * @property integer $id
 * @property integer $unidade_medida
 * @property string $descricao
 * @property double $valor_unitario
 * @property integer $ativo
 *
 * @property UnidadeMedida $unidadeMedida
 * @property HistoricoAtividade[] $historicoAtividades
 */
abstract class BaseAtividade extends GxActiveRecord {

    public $empreendimento;

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'atividade';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Atividade|Atividades', $n);
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('unidade_medida, descricao, valor_unitario, ativo', 'required'),
            array('unidade_medida, ativo', 'numerical', 'integerOnly' => true),
            array('valor_unitario', 'numerical'),
            array('descricao', 'length', 'max' => 255),
            array('id, unidade_medida, descricao, valor_unitario, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'unidadeMedida' => array(self::BELONGS_TO, 'UnidadeMedida', 'unidade_medida'),
            'historicoAtividades' => array(self::HAS_MANY, 'HistoricoAtividade', 'atividade'),
            'empreendimento' => array(self::HAS_MANY, 'Empreendimento', array('empreendimento' => 'id'), 'through' => 'unidadeMedida'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'unidade_medida' => null,
            'descricao' => Yii::t('app', 'Descrição'),
            'valor_unitario' => Yii::t('app', 'Valor Unitário'),
            'unidadeMedida' => null,
            'historicoAtividades' => null,
            'ativo' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('unidade_medida', $this->unidade_medida);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('valor_unitario', $this->valor_unitario);
        $criteria->compare('t.ativo', 1);

        $criteria->with = array('unidadeMedida', 'empreendimento');
        $criteria->together = true;
        $criteria->compare('empreendimento.id', $this->empreendimento, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
