<?php

/**
 * This is the model base class for the table "material".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Material".
 *
 * Columns in table "material" available as properties of the model,
 * followed by relations of table "material" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property double $consumo
 * @property integer $categoria
 * @property integer $ativo
 *
 * @property Categoria $categoria0
 * @property Movimentacao[] $movimentacoes
 */
abstract class BaseMaterial extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'material';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Material|Materiais', $n);
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao, consumo, categoria', 'required'),
            array('consumo', 'numerical'),
            array('categoria, ativo', 'numerical', 'integerOnly' => true),
            array('descricao', 'length', 'max' => 255),
            array('ativo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, descricao, consumo, categoria, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'categoria0' => array(self::BELONGS_TO, 'Categoria', 'categoria'),
            'movimentacoes' => array(self::HAS_MANY, 'Movimentacao', 'material'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'descricao' => Yii::t('app', 'Descrição'),
            'consumo' => Yii::t('app', 'Consumo Total'),
            'categoria' => null,
            'ativo' => Yii::t('app', 'Ativo'),
            'categoria0' => null,
            'movimentacoes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('consumo', $this->consumo);
        $criteria->compare('categoria', $this->categoria);
        $criteria->compare('ativo', 1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
