<?php

/**
 * This is the model base class for the table "unidade_medida".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnidadeMedida".
 *
 * Columns in table "unidade_medida" available as properties of the model,
 * followed by relations of table "unidade_medida" available as properties of the model.
 *
 * @property integer $id
 * @property integer $empreendimento
 * @property string $descricao
 * @property integer $tipo_unidade_medida
 * @property integer $ativo
 *
 * @property Atividade[] $atividades
 * @property TipoUnidadeMedida $tipoUnidadeMedida
 * @property Empreendimento $empreendimento0
 */
abstract class BaseUnidadeMedida extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'unidade_medida';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Unidade de Medida|Unidades de Medida', $n);
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('empreendimento, descricao, tipo_unidade_medida, ativo', 'required'),
            array('empreendimento, tipo_unidade_medida, ativo', 'numerical', 'integerOnly' => true),
            array('descricao', 'length', 'max' => 255),
            array('id, empreendimento, descricao, tipo_unidade_medida', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'atividades' => array(self::HAS_MANY, 'Atividade', 'unidade_medida'),
            'tipoUnidadeMedida' => array(self::BELONGS_TO, 'TipoUnidadeMedida', 'tipo_unidade_medida'),
            'empreendimento0' => array(self::BELONGS_TO, 'Empreendimento', 'empreendimento'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'empreendimento' => null,
            'descricao' => Yii::t('app', 'Descrição'),
            'tipo_unidade_medida' => Yii::t('app', 'Tipo Unidade de Medida'),
            'ativo' => Yii::t('app', 'Ativo'),
            'atividades' => null,
            'tipoUnidadeMedida' => null,
            'empreendimento0' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('empreendimento', $this->empreendimento);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('tipo_unidade_medida', $this->tipo_unidade_medida);
        $criteria->compare('ativo', 1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
