<?php

/**
 * This is the model base class for the table "tipo_unidade_medida".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoUnidadeMedida".
 *
 * Columns in table "tipo_unidade_medida" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $tabela
 * @property integer $ativo
 *
 */
abstract class BaseTipoUnidadeMedida extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tipo_unidade_medida';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'TipoUnidadeMedida|TipoUnidadeMedidas', $n);
    }

    public static function representingColumn() {
        return 'tabela';
    }

    public function rules() {
        return array(
            array('tabela, ativo', 'required'),
            array('ativo', 'numerical', 'integerOnly' => true),
            array('tabela', 'length', 'max' => 255),
            array('id, tabela', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'tabela' => Yii::t('app', 'Tabela'),
            'ativo' => Yii::t('app', 'Ativo'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('tabela', $this->tabela, true);
        $criteria->compare('ativo', 1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
