<?php

/**
 * This is the model base class for the table "tipo_movimentacao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoMovimentacao".
 *
 * Columns in table "tipo_movimentacao" available as properties of the model,
 * followed by relations of table "tipo_movimentacao" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property integer $ativo
 *
 * @property Movimentacao[] $movimentacoes
 */
abstract class BaseTipoMovimentacao extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tipo_movimentacao';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Tipo|Tipos', $n);
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao', 'required'),
            array('ativo', 'numerical', 'integerOnly' => true),
            array('descricao', 'length', 'max' => 255),
            array('ativo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, descricao, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'movimentacoes' => array(self::HAS_MANY, 'Movimentacao', 'tipo_movimentacao'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'descricao' => Yii::t('app', 'Descricao'),
            'ativo' => Yii::t('app', 'Ativo'),
            'movimentacoes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('ativo', $this->ativo);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
