<?php

/**
 * This is the model base class for the table "categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categoria".
 *
 * Columns in table "categoria" available as properties of the model,
 * followed by relations of table "categoria" available as properties of the model.
 *
 * @property integer $id
 * @property integer $empreendimento
 * @property string $descricao
 * @property integer $consumo
 * @property integer $ativo
 *
 * @property Empreendimento $empreendimento0
 * @property Material[] $materiais
 */
abstract class BaseCategoria extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'categoria';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Categoria|Categorias', $n);
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao', 'required'),
            array('empreendimento, consumo, ativo', 'numerical', 'integerOnly' => true),
            array('descricao', 'length', 'max' => 255),
            array('empreendimento, consumo, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, empreendimento, descricao, consumo, ativo', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'empreendimento0' => array(self::BELONGS_TO, 'Empreendimento', 'empreendimento'),
            'materiais' => array(self::HAS_MANY, 'Material', 'categoria'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'empreendimento' => null,
            'descricao' => Yii::t('app', 'Descricao'),
            'consumo' => Yii::t('app', 'Consumo'),
            'ativo' => Yii::t('app', 'Ativo'),
            'empreendimento0' => null,
            'materiais' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('empreendimento', $this->empreendimento);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('consumo', $this->consumo);
        $criteria->compare('ativo', $this->ativo);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                'defaultOrder'=>'descricao ASC',
            ),
            'pagination'=>array(
                'pageSize' => 40,
            ),
        ));
    }

}
